### PR TITLE
Newsletter

### PR DESCRIPTION
**Pull request by sarojabamra**
Finished the newsletters page, work on the individual newsletters still needs to be done.

### CODE REVIEW

**Comment by ItsAnkan** [comment]
my linter is going haywire ;-;
why spaces

**Comment by Goose-Of-War** [comment]
> my linter is going haywire ;-; why spaces

where spaces?

**Comment by ItsAnkan** [comment]
also... put the newsletter components inside a separate directory in components (like textarea)

**Comment by ItsAnkan** [comment]
@Goose-Of-War check now onegai, should be everything

**Comment by ItsAnkan** [comment]
goos review pls

**Review by Goose-Of-War — APPROVED** [review]
Looks good. Needs more work though

**Pull request merged**
