### PR TITLE
Homepage Backend Compatibility

### PR DESCRIPTION
**Pull request by destryptor**
Backend compatibility for homepage added. Please review.

### CODE REVIEW

**Review by Goose-Of-War — APPROVED** [review]
Looking good

**Review by Signor-Koala — CHANGES_REQUESTED** [review]
Small nitpick, but you may need to run file through the linter
Otherwise, LGTM

**Comment by Goose-Of-War** [comment]
@Signor-Koala linted

**Review by Signor-Koala — APPROVED** [review]

**Comment by Signor-Koala** [comment]
Looks good

**Pull request merged**
