### PR TITLE
README Update

### PR DESCRIPTION
**Pull request by Goose-Of-War**
Provides some basic information about the repository. Needs elaboration. Would appreciate it if y'all could suggest stuff to add.

Used the [event repository](https://github.com/kgpmask/MASK-Event) as a base for this README (yes, I wrote that too; how'd you know?)

### CODE REVIEW

**Review by Signor-Koala — APPROVED** [review]
Looks good to me
maybe add some information on how the project is structured (i.e. the folder and file layout)

**Comment by Goose-Of-War** [comment]
Will add that ig

**Comment by destryptor** [comment]
Looks perfect to me, given the stuff we are using right now. No more additions from my side, after koala suggested the project structure.

**Review by ItsAnkan — APPROVED** [review]
works for me

**Review by destryptor — COMMENTED** [review]
Looks really good, as i said in my previous comment.

**Review by destryptor — APPROVED** [review]

**Comment by SachdevJai** [comment]
LGTM maybe add a section describing how it would interact with the backend api?

**Comment by Goose-Of-War** [comment]
> LGTM maybe add a section describing how it would interact with the backend api?

Will be done once Koala's done with the backend

**Review by SachdevJai — APPROVED** [review]
cool then
mask->next it is

**Pull request merged**
