### PR TITLE
Make basic skeleton of the database backend

### PR DESCRIPTION
**Pull request by Signor-Koala**

### CODE REVIEW

**Review by Goose-Of-War — COMMENTED** [review]
Looks good. You can yeet the "Additional checks" comment and test model and we are good to go from my side (especially since this is just the skeleton and no APIs)

**Comment by Signor-Koala** [comment]
> Looks good. You can yeet the "Additional checks" comment and test model and we are good to go from my side (especially since this is just the skeleton and no APIs)

Have done so, and awaiting further work soon

**Review by Goose-Of-War — APPROVED** [review]
Lessgo in that case. Will wait for @destryptor to see if he wants to add something (for like an hour or so)

**Review by destryptor — COMMENTED** [review]
I am on my phone right now, but I have checked everything. Seems pretty good to me. I can't find an option to approve, so I'm submitting this review. Take this as my approval please. 
Arigato gosaimasu koala san

**Comment by Goose-Of-War** [comment]
@Signor-Koala next time give a ping before you merge n.n

**Pull request merged**
